class BankAccount {
    public static void main(String[] args) {
        
        String owner_name;
        String owner_surname;
        String owner_id;
        
        
        static void print_balance() {
             System.out.println("");}
             
        static void withdraw() {
             System.out.println(""");}
             
        static void deposit() {
            System.out.println("");}

        System.out.println("");
    }
}
